name: reseau_auto
description: "Application Reseau Pieces Afrique"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.4 # 🟢 Mise à niveau synchronisée avec notre whisper_service
  geolocator: ^14.0.2
  image_picker: ^1.2.2
  record: ^6.2.0            # 🎙️ Capture micro préservée pour l'atelier
  path_provider: ^2.1.5
  just_audio: ^0.10.5       # 🎵 Conservé en solo (Purger audioplayers résout le crash A10)
  vibration: ^3.1.8
  shared_preferences: ^2.5.5
  http: ^1.2.0              # 👈 LE CONNECTEUR CLOUD VERS OPENAI / SUPABASE INJECTÉ ICI
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sirene.ogg     # 👈 LE FILTRE DE DOUANE MULTIMÉDIA EMBARQUÉ
